---
firefox:
  - addon_dir: /usr/share/firefox-addons
basic_auth:
  - username: admin
  - password: secret
store_manager:
  - username: webtests
  - password: secret
test_user:
  - email: webtests@alias.commercetools.de
gmail:
  - username: webtests@commercetools.de
  - password: secret
saucelabs:
  - username:
  - access_key:
