---
plain: --no-profile
video: RECORD_ALL_VIDEOS=true
headless: HEADLESS=true
failfast: FAIL_FAST=true
verbose: VERBOSE=true
sbs: STEP_BY_STEP=true
ignore_proxy: IGNORE_PROXY=true
ignore_basic_auth: IGNORE_BASIC_AUTH=true
manual: --tags @interactive
auto: --tags ~@interactive --tags ~@wip
# There is a bug in cucumber - so please run 'cucumber -p wip --dry-run'
wip: --color --no-snippets --dry-run --wip --tags @wip
# check for workspace directory
<% ws = ENV['WORKSPACE'].nil? ? "." : ENV['WORKSPACE'] %>
ci: --profile auto --profile headless --strict --quiet --color --format pretty --format junit --out <%= ws %>/results --format rerun --out <%= ws %>/rerun.txt --format usage --out <%= ws %>/usage.colored.txt
debug: --format debug --backtrace --verbose
# Support common names of environments via profiles
vagrant: --profile auto SYSTEM_UNDER_TEST="vagrant"
staging: --profile auto SYSTEM_UNDER_TEST="staging"
production: --profile auto SYSTEM_UNDER_TEST="production" --tags ~@staging
